### ISSUE TITLE
license

### ISSUE THREAD

**Issue by lazarusA** [yairEO/hover-carousel#1]
I noticed that a license is not available. What are the terms/conditions for using this?
Going for and MIT license will help others to use this pretty easy.

**Comment by yairEO** [comment]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

I simply use the default one, so none should be specified.

**Comment by lazarusA** [comment]
I see, namely,
`no one may reproduce, distribute, or create derivative works from your work`.
thanks.

**Comment by yairEO** [comment]
You wanted to re-distribute my component as yours?
